### ISSUE TITLE
Not recognizing .stylelintrc.yml?

### ISSUE THREAD

**Issue by logue** [ModyQyW/vite-plugin-stylelint#1]
I'm writing stylelintrc in yaml, but when I get the error "No rules found within configuration. Have you provided a" rules "property?", It seems that the settings there are not loaded.

For reference, the settings are as follows:
```yml
extends:
  - stylelint-config-html/vue
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-prettier
plugins:
  - stylelint-order
  - stylelint-prettier
  - stylelint-scss
ignoreFiles:
  - 'dist/**/*'
rules:
  prettier/prettier: true
  color-function-notation: legacy
  scss/no-global-function-names: null
```
