### ISSUE TITLE
Indentation error?

### ISSUE THREAD

**Issue by iammati** [ModyQyW/vite-plugin-stylelint#5]
Hi there,

got this configuration inside `stylelint.config.js`:
```js
module.exports = {
    extends: 'stylelint-config-standard',
    customSyntax: 'postcss-scss',

    rules: {
        indentation: 4,
        'no-missing-end-of-source-newline': true,
        'string-quotes': 'single',
        'no-missing-end-of-source-newline': null,
    },
}
```

and this inside my `vite.config.ts`:
```ts
const configuration: UserConfig = {
    plugins: [
        StylelintPlugin({
            emitWarningAsError: true,
            throwOnWarning: true,
            throwOnError: true,
            include: [
                './src/Scss/**/*.scss',
            ],
            exclude: [
                /node_modules/,
            ],
        }),
    ],
    ...
  }
```

My `app.scss` file looks like this:
```scss
/* stylelint-disable */
@import '@iammati/cookiebox/src/Cookiebox.scss';
/* stylelint-enable */

body {
    background-color: #fefefe !important;
}
```

Note that I got 4 spaces indentation inside my `app.scss`, also configured that in stylelint configuration ruleset.

But for some reason I get the following warning inside my terminal:
![image](https://user-images.githubusercontent.com/41418763/161242508-ec179f04-6768-4dda-86dc-365ffca9de55.png)

As soon as I try to use 2 instead of 4 spaces inside my scss file it throws the error that I should use 4 spaces, but then again this throws the warning that I'm using 2 instead of 4?
